### ISSUE TITLE
1.19.2 backport and 1.20 update?

### ISSUE THREAD

**Issue by mateus3c** [Superkat32/PostmortalParticles#3]
I just notice your the same dev of Explosive Enhancement
I literally just installed 1.19.4 to test this mod (never really played 1.19.4) and I really like it, I play on an 1.19.2 modpack and I kinda miss having this super cool visual effect while fighting tons of pillagers lol

Are there any plans to update to 1.20 and who knows even a 1.19.2 backport? (no pressure of course)

**Comment by Superkat32** [comment]
If you'd use a 1.19.2 port, I can certainly give it a try! I didn't initially make a 1.19.2 port because I didn't think anyone would use it, then I started my own 1.19.2 modpack and really missed this mod. I might as well get a 1.19.3 port done while I'm at it.

A 1.20 port is planned, just not in the works yet. My goal is to port my mods to 1.20 in this order.
Explosive Enhancement(already has a 1.20-pre2 port, shouldn't take long)
Postmortal Particles(hopefully port goes well)
Broken Lead Warner(still needs a 1.19.4 port, will take extra time)
Sparkling Strikes(possibly, it was really an experiment more than anything, and isn't really practical in gameplay)

I will post a couple update comments whenever I start work on porting this mod, and whenever I have made some good progress on it. No estimated timeline as of now, as I do all of my modding in my free time. 👍

**Comment by Superkat32** [comment]
If you'd use a 1.19.2 port, I can certainly give it a try! I didn't initially make a 1.19.2 port because I didn't think anyone would use it, then I started my own 1.19.2 modpack and really missed this mod. I might as well get a 1.19.3 port done while I'm at it.

A 1.20 port is planned, just not in the works yet. My goal is to port my mods to 1.20 in this order.
Explosive Enhancement(already has a 1.20-pre2 port, shouldn't take long)
Postmortal Particles(hopefully port goes well)
Broken Lead Warner(still needs a 1.19.4 port, will take extra time)
Sparkling Strikes(possibly, it was really an experiment more than anything, and isn't really practical in gameplay)

I will post a couple update comments whenever I start work on porting this mod, and whenever I have made some good progress on it. No estimated timeline as of now, as I do all of my modding in my free time. 👍

**Comment by mateus3c** [comment]
> If you'd use a 1.19.2 port, I can certainly give it a try! I didn't initially make a 1.19.2 port because I didn't think anyone would use it, then I started my own 1.19.2 modpack and really missed this mod. I might as well get a 1.19.3 port done while I'm at it.
> 
> A 1.20 port is planned, just not in the works yet. My goal is to port my mods to 1.20 in this order. Explosive Enhancement(already has a 1.20-pre2 port, shouldn't take long) Postmortal Particles(hopefully port goes well) Broken Lead Warner(still needs a 1.19.4 port, will take extra time) Sparkling Strikes(possibly, it was really an experiment more than anything, and isn't really practical in gameplay)
> 
> I will post a couple update comments whenever I start work on porting this mod, and whenever I have made some good progress on it. No estimated timeline as of now, as I do all of my modding in my free time. 👍

thats awesome to know, thank you so much for your hard work!

**Comment by Superkat32** [comment]
Mods ported to 1.20
✔️ Explosive Enhancement
✔️ Postmortal Particles
✔️  Broken Lead Warner
✔️  You Were Slain

Work on the 1.19.2 port has started. 🙃 

(Also, idk why my last message duplicated.)

**Comment by Superkat32** [comment]
Postmortal Particles has been ported to 1.20.0 and 1.20.1! Requires YACL v3.

https://modrinth.com/mod/postmortal-particles/version/1.0.0-1.20.x
_(Modrinth might need a few minutes to show you the version. If it doesn't work, try again in a little bit)_

**Comment by Superkat32** [comment]
1.19.2 and 1.19.3 backports are being worked on!

✔️ 1.19.2
✔️  1.19.3

Trying to get things done before heading to bed tonight. Thanks for your patience! 😄

**Comment by Superkat32** [comment]
Postmortal Particles has been backported to 1.19.2 and 1.19.3!

https://modrinth.com/mod/postmortal-particles/version/1.0.0-1.19.2

Thanks for your suggestion!

**Comment by mateus3c** [comment]
> Postmortal Particles has been backported to 1.19.2 and 1.19.3!
> 
> https://modrinth.com/mod/postmortal-particles/version/1.0.0-1.19.2
> 
> Thanks for your suggestion!

just saw it!!! Im very excited to start playing with Postmortal Particles on my modpack! thank you so much!!
