### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [Superkat32/PostmortalParticles#8]
inability to open configuration menu with LabyMod

**Comment by Superkat32** [comment]
This might be an issue with LabyMod, YetAnotherConfigLib(YACL), or Mod Menu. Historically, mod clients(like LabyMod it seems) do not play nice with manually added mods, but I am unfamiliar with how LabyMod handles things.

Beyond that, I'm going to need more information.
- What Minecraft version are you using?
- Can you send screenshots showing how you would normally edit a mod's config with LabyMod, and what's going wrong with trying to edit Postmortal Particles' config? Are there any errors that appear or does the edit button just not show up/not work?

I'm closing this early because I'm pretty sure there isn't anything I can do about it from Postmortal Particles' side, but I can try to help beyond that. Alternatively, you should be able to edit the config file directly from file explorer if everything else fails.
